### ISSUE TITLE
Possibly add an argument for a cleaner error output

### ISSUE THREAD

**Issue by shmup** [mrtazz/checkmake#21]
It'd be nice if there was  a way to output a format that was better for vim's `errorformat` (more things than vim could leverage this), so, not having the Description be split onto two lines for example, i.e.:

```
    RULE              DESCRIPTION             LINE NUMBER

  minphony   Missing required phony target    0
             "test"
```

Could output with some argument, as:

`miniphony|missing required phony target "test"|0`

Ultimately I want to run this within vim, and capture the output by specifying the proper errorformat and display in a QuickFix list.

**Comment by mrtazz** [comment]
Is the [custom formatter](https://github.com/mrtazz/checkmake/blob/master/docs/formatting.md) enough for your use case there? I also want this to integrate [nicely with syntastic](https://github.com/mrtazz/checkmake/issues/14) at some point. So using checkmake with vim like that is totally in line with how I think it would be most useful

**Comment by shmup** [comment]
That's perfect! Ha, thanks.
