### ISSUE TITLE
Allow exceptions to timestampexpanded

### ISSUE THREAD

**Issue by JonZeolla** [mrtazz/checkmake#25]
### Expected behaviour
A user should be able to configure a rule that whitelists a string in the `timestampexpanded` rule.  For instance, `update`.

### Output of `checkmake --version`
```
checkmake  built at  by  with
```
(Wow, that output wasn't expected!)

**Comment by mrtazz** [comment]
this makes sense but is essentially a special case of https://github.com/mrtazz/checkmake/issues/31. So I'm closing this in favour of the more general feature. Thanks for submitting!

**Comment by JonZeolla** [comment]
For those looking for a workaround for this issue you could create a blanket `checkmake.ini` that disables `timestampexpanded` entirely:
```bash
[timestampexpanded]
disabled = true
```
