### ISSUE TITLE
wish: more recent binary executables for Debian....

### ISSUE THREAD

**Issue by bstarynk** [mrtazz/checkmake#47]
**The `*.deb` files are four years old!**

It would be nice to have more recent binary packages (e.g. for Debian/Buster x86-64 or Ubuntu/20.04/x86-64)

I would like to use `checkmake` for both [Bismon](https://github.com/bstarynk/bismon) - my professional project - and [RefPerSys](http://refpersys.org/) (my hobby project)

Regards from near Paris, France.

[Basile Starynkevitch](http://starynkevitch.net/Basile/index_en.html) - email <basile@starynkevitch.net>

**Comment by jsirianni** [comment]
I know this is not the answer you are looking for but it might be good enough

You can build the project on windows or macos like this
```
export GOOS=linux
go build
```
Or on Linux
```
go build
```

The resulting Linux binary will run fine under Debian.

**Comment by mrtazz** [comment]
there's now a new tag with corresponding packages at https://github.com/mrtazz/checkmake/releases/tag/0.2.0
