### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by s22-rxr** [mrtazz/checkmake#52]
### Expected behaviour
docker build succeeds
### Actual behaviour
run 'docker build . -t checker` from root of dir

error:
```
 => ERROR [builder 3/4] RUN cd /go/src/github.com/mrtazz/checkmake && GOO  0.4s
------
 > [builder 3/4] RUN cd /go/src/github.com/mrtazz/checkmake && GOOS=linux GOARCH=amd64 CGO_ENABLED=0 make binaries:
#10 0.327 /bin/sh: 1: cd: can't cd to /go/src/github.com/mrtazz/checkmake
------
executor failed running [/bin/sh -c cd /go/src/github.com/mrtazz/checkmake && GOOS=linux GOARCH=amd64 CGO_ENABLED=0 make binaries]: exit code: 2
```
### Output of `checkmake --version`

n/a 

### Output of `checkmake --debug <your makefile>`

n/a

### Output of `make --version`

GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0

**Comment by mrtazz** [comment]
fixed in https://github.com/mrtazz/checkmake/pull/51
