### ISSUE TITLE
Install checkmake on alpine linux ?

### ISSUE THREAD

**Issue by nvuillam** [mrtazz/checkmake#71]
I'd like to embed checkmake within [MegaLinter](https://oxsecurity.github.io/megalinter/latest/)

Is there a known way to install it on alpine linux ?

Many thanks !

**Comment by wesley-dean-flexion** [comment]
I use a Dockerfile that creates an Alpine-backed image:

```Dockerfile
ARG CHECKMAKE_VERSION=0.2.1
ARG CHECKMAKE_ARCH=amd64

FROM alpine
ARG CHECKMAKE_VERSION
ARG CHECKMAKE_ARCH
WORKDIR /tmp
RUN ( [ -d /usr/local/bin ] || mkdir -p /usr/local/bin ) \
  && wget "https://github.com/mrtazz/checkmake/releases/download/$CHECKMAKE_VERSION/checkmake-$CHECKMAKE_VERSION.linux.$CHECKMAKE_ARCH" -O /usr/local/bin/checkmake \
  && chmod 755 /usr/local/bin/checkmake
ENTRYPOINT ["/usr/local/bin/checkmake"]
```

To run it, I use:
```bash
docker run -v "$(pwd):$(pwd)" -w "$(pwd)" checkmake-alpine Makefile
```

(assuming the image was tagged `checkmake-alpine`)

The guts (downloading via `wget` and using `chmod` to make it executable) ought to be sufficient for downloading, installing, and using it outside of a containerized context.

**Comment by nvuillam** [comment]
That seems great,I'll try that, thanks :)

**Comment by mrtazz** [comment]
closing this since the suggested solution seems to work. Feel free to reopen if needed.
