### ISSUE TITLE
Support PHONY variable

### ISSUE THREAD

**Issue by rasa** [mrtazz/checkmake#73]
Support:
```makefile
PHONY += all
all:
   true
   
.PHONY: ${PHONY}
```
It currently gives the error:
`Target "all" should be declared PHONY`

**Comment by mrtazz** [comment]
I don't think we can reasonably support runtime variables in a static linter like this because this more or less requires us to be able to execute the Makefile and inspect generated variable content. 

Please feel free to reopen this issue if anyone has a suggestion how to do this.
